language: node_js

node_js:
- "lts/*"

os:
- linux
- osx

branches:
  only:
  - master
  
cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@latest

install:
- npm install

script:
- ava test/organize-array/organize-array.test.js --fail-fast